projects_dir_win: 
templates_dir_win: 
projects_dir_mac: 
templates_dir_mac: 
pipeline_dir_name: 00_pipeline
work_dir_name: 02_work
dailies_dir_name: 03_dailies
deliveries_dir_name: 04_deliveries
extra_dir_names:
  - 01_preproduction

# The first subdir is the work-dir, the second is the output-dir.
work_sub_dirs:
  - 01_work
  - 02_output
  - 03_assets

ignore_extensions:
  - test
